# -*- coding: utf-8 -*-
"""DialogFlowBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3P0f3t3rDnsslfj-PnlIhVM2QFE47LE
"""

# ✅ Install Dialogflow client library
!pip install google-cloud-dialogflow

# ✅ Import required libraries
import os
from google.cloud import dialogflow_v2 as dialogflow
from IPython.display import display
import ipywidgets as widgets

# ✅ Set path to your service account key
SERVICE_ACCOUNT_FILE = "dialogflow-key.json"  # Make sure this matches uploaded file name
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = SERVICE_ACCOUNT_FILE

# ✅ Set your Dialogflow project ID here
PROJECT_ID = "customersupportbot-lvuh"  # 🔁 Replace this

# ✅ Function to detect intent using Dialogflow
def detect_intent_texts(text, session_id="user-session", language_code="en"):
    session_client = dialogflow.SessionsClient()
    session = session_client.session_path(PROJECT_ID, session_id)

    text_input = dialogflow.types.TextInput(text=text, language_code=language_code)
    query_input = dialogflow.types.QueryInput(text=text_input)

    response = session_client.detect_intent(
        request={"session": session, "query_input": query_input}
    )

    return response.query_result.fulfillment_text

# ✅ Create simple UI with widgets
input_box = widgets.Text(
    value='',
    placeholder='Type your question...',
    description='You:',
    layout=widgets.Layout(width='100%')
)
output_box = widgets.Output()

def on_submit(change):
    output_box.clear_output()
    user_text = change.new
    if user_text.strip():
        reply = detect_intent_texts(user_text)
        with output_box:
            print(f"🤖 Bot: {reply}")

input_box.observe(on_submit, names='value')

# ✅ Display chatbot UI
display(input_box, output_box)