# -*- coding: utf-8 -*-
"""telegrambot_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MzwVUxtFfRaJ71hDnaeU3y5Tl5zpnuF
"""

import os
import asyncio
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters
import google.cloud.dialogflow_v2 as dialogflow

# Set your Dialogflow credentials file path
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "dialogflow-key.json"

PROJECT_ID = "customersupportbot-lvuh"

# Dialogflow intent detection
async def detect_intent_texts(text, session_id="123456", language_code="en"):
    session_client = dialogflow.SessionsClient()
    session = session_client.session_path(PROJECT_ID, session_id)

    text_input = dialogflow.TextInput(text=text, language_code=language_code)
    query_input = dialogflow.QueryInput(text=text_input)

    response = session_client.detect_intent(request={"session": session, "query_input": query_input})
    return response.query_result.fulfillment_text

# /start command
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Hi! I’m your support bot. How can I help you today?")

# Handle user messages
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_text = update.message.text
    reply = await detect_intent_texts(user_text)
    await update.message.reply_text(reply)

# Entry point
def main():
    # Read from the environment - never hardcode the token. A token committed
    # to a repository is a published credential: anyone who reads it can
    # receive this bot's messages and reply as it. Set it before running:
    #   Windows : set TELEGRAM_BOT_TOKEN=your-token
    #   Linux   : export TELEGRAM_BOT_TOKEN=your-token
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    if not token:
        raise SystemExit(
            "TELEGRAM_BOT_TOKEN is not set. Get a token from @BotFather and "
            "export it before running this script."
        )

    app = ApplicationBuilder().token(token).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    print("Bot is running...")
    # Without this the script builds the application, registers the handlers,
    # prints "Bot is running..." and exits immediately - the bot never polls
    # Telegram and never answers a single message.
    app.run_polling()


if __name__ == "__main__":
    try:
        main()
    except RuntimeError:
        # Notebook environments (Colab, Jupyter) already run an event loop,
        # which run_polling() cannot start inside. nest_asyncio allows the
        # nested loop - then actually retry, rather than patching and exiting.
        import nest_asyncio

        nest_asyncio.apply()
        main()