# -*- coding: utf-8 -*-
"""FutureInternsML Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrciym2Bc1TOxBmZAh0qpEhkRBjPOIZ0
"""

# Colab magic, not valid Python - a bare `pip install` line makes this file a
# SyntaxError when run outside a notebook. Install the dependencies first:
#   pip install pandas numpy scikit-learn xgboost matplotlib seaborn openpyxl

from pathlib import Path

import pandas as pd

df = pd.read_csv(Path(__file__).with_name("TelcoCustomerChurn.csv"))

print(df.shape)
df.head()

df.drop('customerID', axis=1, inplace=True)

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

cat_cols = df.select_dtypes(include=['object']).columns

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

df.head()

from sklearn.model_selection import train_test_split

X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

# Scaled inside a pipeline: tenure runs 0-72 while MonthlyCharges runs to ~120
# and the one-hot columns are 0/1, so on raw features lbfgs hit max_iter
# without converging. The pipeline applies the scaler on every fit/predict,
# so the model is still called with raw X everywhere below.
log_reg = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))
rf = RandomForestClassifier(random_state=42)
xgb = XGBClassifier(eval_metric='logloss', random_state=42)

# Train
log_reg.fit(X_train, y_train)
rf.fit(X_train, y_train)
xgb.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

def evaluate_model(model, name):
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:,1]
    print(f"Model: {name}")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(f"ROC AUC: {roc_auc_score(y_test, y_proba)}\n")

evaluate_model(log_reg, "Logistic Regression")
evaluate_model(rf, "Random Forest")
evaluate_model(xgb, "XGBoost")

import matplotlib.pyplot as plt
import seaborn as sns

# Importances are read from XGBoost even though Logistic Regression is the
# exported model: tree importances are scale-invariant, whereas ranking
# logistic coefficients would mostly rank the features' units.
feature_importance = pd.Series(xgb.feature_importances_, index=X.columns)
feature_importance.nlargest(10).plot(kind='barh')
plt.title('Top 10 Important Features')
plt.show()

# Logistic Regression is exported, not XGBoost: it scored higher on both
# accuracy and ROC AUC on this dataset (see README). Churn here is driven by a
# few strong, largely linear signals, so the ensembles' extra capacity fits
# noise rather than signal.
predictions = pd.DataFrame()
predictions['Churn_Probability'] = log_reg.predict_proba(X_test)[:,1]
predictions['Actual'] = y_test.values
predictions['Predicted'] = log_reg.predict(X_test)
predictions.head()

X_test_copy = X_test.copy()
# .values, not the Series: `predictions` was built with a fresh 0..n-1 index
# while X_test keeps the shuffled index from train_test_split. Assigning the
# Series makes pandas align on index, so only the few rows whose original
# index happened to fall in 0..n-1 got a value and the rest became NaN -
# 1116 of 1409 rows in the previously exported workbook.
X_test_copy['Churn_Probability'] = predictions['Churn_Probability'].values
X_test_copy['Actual'] = y_test.values
X_test_copy['Predicted'] = predictions['Predicted'].values

X_test_copy.to_excel("Churn_Prediction_Output.xlsx", index=False)

sns.countplot(x='Actual', data=predictions)
plt.title("Churn vs Non-Churn")
plt.show()